### ISSUE TITLE
ez

### ISSUE THREAD

**Issue by Jude-Gideon** [epw123124/mw2-cheat#1]

**Comment by epw123124** [comment]
what u mean by that

**Comment by epw123124** [comment]
did u run it in admin mode?

**Comment by Jude-Gideon** [comment]
Yes, as I said it's broken.

**Comment by epw123124** [comment]
do u got node.js installed?

**Comment by Jude-Gideon** [comment]
> do u got node.js installed?

Nice token logger!!!!! You tried so hard to scam my friends and my entire Discord but failed.

**Comment by Jude-Gideon** [comment]
I don't have dogshit grammar and spelling like you.

**Comment by epw123124** [comment]
i didnt failed my guy look at ur bank statement:skull:
